# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.CharField(max_length=250)),
                ('years_lived', models.DateTimeField(verbose_name='Years lived in')),
                ('security_deposit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LandLord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
            ],
        ),
    ]
