# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='move_in',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Moved in'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='years_lived',
            field=models.PositiveSmallIntegerField(verbose_name='Years lived in'),
        ),
    ]
