# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentar', '0002_auto_20161022_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='move_in',
            field=models.DateField(verbose_name='Moved in'),
        ),
    ]
