# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentar', '0003_auto_20161022_1846'),
        ('rentar', '0002_auto_20161027_2039'),
    ]

    operations = [
    ]
