# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentar', '0004_merge_20161027_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField()),
                ('years_lived', models.PositiveSmallIntegerField(default=0)),
                ('starting_rent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ending_rent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pet_fee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('water', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('heat', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('electric', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('garbage', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('parking', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('neighborhood', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('location', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('landlord', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('privacy', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('responsiveness', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('maintenance', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('likeability', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('comment', models.TextField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='address_text',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='move_in',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='years_lived',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='name_text',
        ),
        migrations.AddField(
            model_name='apartment',
            name='address_line',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='apartment',
            name='attic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='avg_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='apartment',
            name='avg_security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='apartment',
            name='basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bathrooms',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='apartment',
            name='bedrooms',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='apartment',
            name='dining_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='dryer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='electric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='garbage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='heat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentar.Landlord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='living_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='parking_offstreet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='parking_onstreet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='public_transportation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='secondary_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='state',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='apartment',
            name='washer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='zipcode',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='landlord',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='landlord',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='landlord',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='landlord_rating',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentar.Apartment'),
        ),
        migrations.AddField(
            model_name='landlord_rating',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentar.Landlord'),
        ),
        migrations.AddField(
            model_name='apartment_rating',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentar.Apartment'),
        ),
    ]
