# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentar', '0005_auto_20161027_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord_rating',
            name='apartment',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentar.Landlord'),
        ),
        migrations.AlterField(
            model_name='landlord_rating',
            name='hot',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='landlord_rating',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentar.Landlord'),
        ),
        migrations.AlterField(
            model_name='landlord_rating',
            name='likeability',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='landlord_rating',
            name='maintenance',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='landlord_rating',
            name='privacy',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='landlord_rating',
            name='responsiveness',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
