# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentar', '0006_auto_20161027_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentar.Landlord'),
        ),
        migrations.AlterField(
            model_name='landlord_rating',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentar.Landlord'),
        ),
    ]
