# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentar', '0008_auto_20161028_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlord_rating',
            name='landlord',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='avg_rent',
            new_name='rent',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='avg_security_deposit',
            new_name='security_deposit',
        ),
        migrations.RenameField(
            model_name='apartment_rating',
            old_name='landlord',
            new_name='landlord_hot',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='landlord',
        ),
        migrations.AddField(
            model_name='apartment',
            name='landlord_company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='apartment',
            name='landlord_first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='apartment',
            name='landlord_last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='apartment_rating',
            name='landlord_maintenance',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment_rating',
            name='landlord_privacy',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment_rating',
            name='landlord_responsiveness',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LandLord',
        ),
        migrations.DeleteModel(
            name='Landlord_Rating',
        ),
    ]
